### PR TITLE
Update CI builds and add ctrueden as maintainer

### PR DESCRIPTION
**Pull request by imagejan**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR bundles various trials to fix the CI build <s>and finally bump to version 1.3.0 of pyjnius</s>.

I cherry-picked @hanslovsky's commit adding @ctrueden as new maintainer.

### CODE REVIEW

**Comment by imagejan** [comment]
@conda-forge-admin, please rerender

**Review by hanslovsky — APPROVED** [review]

**Comment by ctrueden** [comment]
All checks have passed! @imagejan you are the best! 🍻

**Comment by imagejan** [comment]
Unfortunately, the build issues with version 1.3.0 aren't fixed yet (#19). 🙁

**Comment by ctrueden** [comment]
So we should merge this (@hanslovsky can you do it?) and then rebase #19 on top of it, and fix the build issues, right? Do I understand correctly?

**Comment by hanslovsky** [comment]
Thank you @imagejan!

**Pull request merged**
