### PR TITLE
Bump to 1.1.3

### PR DESCRIPTION
**Pull request by hadim**
ping @ctrueden and @hanslovsky.

### CODE REVIEW

**Comment by hadim** [comment]
- pyjnius: https://github.com/conda-forge/pyjnius-feedstock/pull/1
- jgo: https://github.com/conda-forge/staged-recipes/pull/7065
- scyjava: https://github.com/conda-forge/staged-recipes/pull/7066
- imagej: https://github.com/conda-forge/staged-recipes/pull/7067
- imglyb: https://github.com/conda-forge/staged-recipes/pull/7068

**Comment by hanslovsky** [comment]
Is there a specific reason to use the commit hash over the tag?

**Comment by hadim** [comment]
Because I think you cannot use tags on conda build recipe or at least I couldn't find it on the documentation.

**Comment by hanslovsky** [comment]
You can, [for example](https://github.com/hanslovsky/conda-build-scripts/blob/master/imglyb/meta.yaml). Maybe we should switch to download the tar ball from the release (instead of checking out the source), anyway. [Numpy](https://github.com/conda-forge/numpy-feedstock/blob/master/recipe/meta.yaml), for example, does that. I will add suggestions to the code.

**Comment by hadim** [comment]
Ok, I didn't know it was possible. I switched to numpy-styled to download the tarball.

Feel free to merge once CIs are happy.

**Comment by hanslovsky** [comment]
Thanks @hadim I will wait until all the checks complete and then I will merge.

**Pull request merged**
