### PR TITLE
Fix OpenJDK to v8

### PR DESCRIPTION
**Pull request by hadim**
https://github.com/kivy/pyjnius/issues/304 needs to be fixed to use OpenJDK >8

Ping @hanslovsky

### CODE REVIEW

**Comment by hanslovsky** [comment]
Looks good to me!

**Comment by hanslovsky** [comment]
Maybe we need to include the JVM version in the package name/make separate packages for each JVM version.  After all, pyjnius built against jvm8 might not be compatible with jvm9.

**Comment by hadim** [comment]
That's a good point. I think Conda has a mechanism for this (similar to what they do with Numpy) but I don't know enough... Maybe @jakirkham could comment?

In the meantime, @hanslovsky can you merge this and I will open an issue about JVM version.

**Comment by hadim** [comment]
See #4.

**Pull request merged**
