### PR TITLE
pyjnius v1.4.1 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Continuing from #27 

Closes #27
Closes #26 
Closes #19

### CODE REVIEW

**Comment by h-vetinari** [comment]
FInally the full test suite running through in the openjdk 8 builds 🥳 
I'd still like to get those test-classe back out of `pyjnius.jar`, but one step at a time...

**Comment by hadim** [comment]
@h-vetinari can you remove me from the list of maintainers please?

**Comment by h-vetinari** [comment]
> @h-vetinari can you remove me from the list of maintainers please?

Tell you what, how about I do that and in turn, you merge this PR (once I've figured out the last few details)? ;-)

**Comment by hadim** [comment]
Yes of course! Ping me when you're done.

**Comment by h-vetinari** [comment]
> @hadim: Yes of course! Ping me when you're done.

I had a better idea (not least since I'm taking another turn here, and it might take a while yet) - I've opened #30, which should be instantly mergeable, and does the maintenance hand-over, as well as some clean-ups that will make reviewing this PR easier.

**Comment by h-vetinari** [comment]
Cannot believe how many dead ends I took to arrive at almost the same place. 🙈 

This has been a time sink of unimaginable proportions for me, but happy it was at least able to crystalise and cross-polinate into the much cleaner #31 now.

**Pull request closed without merging**
